### ISSUE TITLE
Memory Leak on iOS

### ISSUE THREAD

**Issue by thomasconner** [NathanaelA/nativescript-sqlite#108]
On iOS I am seeing the memory for my NativeScript application continue to grow as I execute SQL queries using this plugin. I have written a very basic sample app that demonstrates this problem.

@NathanaelA do you have any idea why I would be seeing this memory leak?

Sample App: https://github.com/thomasconner/nativescript-sqlite-memory-leak

**Comment by NathanaelA** [comment]
@thomasconner - Awesome; I'll check out your issue.    Please note if your app is using angular (which it appears you are); there are several known ios memory leaks that are being resolved right now in both the TNS core modules and Angular.  

I haven't looked at your test app; but if your test app is navigating between screens to do its work; you will see leaks because of the above mentioned mention leaks, without even using ns-sqlite as resources aren't being freed properly.

If your test is just loading data and console logging it on each click and still leaking memory this; it actually might be in ns-sqlite.   :-)

**Comment by thomasconner** [comment]
This seems to be fixed by https://github.com/NativeScript/ios-runtime/pull/1019.
