### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by nraboy** [NathanaelA/nativescript-sqlite#12]
When I try to build on iOS I get the following:

```
Processing node_modules failed. Error: Command failed: /bin/sh -c ruby -e "require 'xcodeproj'; Xcodeproj::Config.new('/Users/nraboy/Desktop/SqlProject/platforms/ios/plugins-debug.xcconfig').merge(Xcodeproj::Config.new('/Users/nraboy/Desktop/SqlProject/node_modules/nativescript-sqlite/platforms/ios/build.xcconfig')).save_as(Pathname.new('/Users/nraboy/Desktop/SqlProject/platforms/ios/plugins-debug.xcconfig'))"
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

Seems to work fine on Android.  Any ideas?

**Comment by NathanaelA** [comment]
Try to do a "**gem install xcodeproj**" and see if that helps.   I don't recall installing xcodeproj; but my machine has it. if NativeScript is attempting to run it, then it needs it for some reason.  Do you a have cocoapods installed, so that when you type "pod" it gives you info on CocoaPods?

**Comment by nraboy** [comment]
I am going to take a guess and say I have none of that installed.

Would it be difficult to remove that dependency?  Apache Cordova doesn't require those dependencies for SQLite in iOS.  I really don't know the difficulty which is why I ask.

Best,

**Comment by NathanaelA** [comment]
I did some looking into this.  This isn't something I'm requiring.   But it comes along when you install cocoapod support (which I've done on my machine, and why I didn't realize it was required until I did some checking.)

This is something that the NativeScript TNS command uses when it is building **any** project that has a external compiled resource/library/framework on iOS.  (Normally these are cocoapods)  Since linking to SQLite requires the metadata generated for it -- it requires the xcodeproj command to generate and change the xcode project.   So if you want to use sqlite or any cocoapod plugins, you need to install cocoapod support.

To install cocoapod support type **sudo gem install cocoapods** at a terminal prompt.  Again, you will need cocoapod support for many of the plugins on iOS, and it is a simple install to get everything working.

**Comment by nraboy** [comment]
I have not run into this issue with other NativeScript plugins, but I see what you're saying.  Might be worth it to add this information to the README as I don't recall seeing it there.

Best,

**Comment by NathanaelA** [comment]
@nraboy - I added it to my readme the other day.  :grinning:
if the plugin is pure JavaScript it won't require cocoapod support.  If the plugin has any compiled item, it requires the cocoapod support.   I think the new TNS version actually will give you an warning during first install if you are missing cocoapod support.

**Comment by nraboy** [comment]
Sounds good :-)
