### ISSUE TITLE
DEMO SQL-COMMERCIAL

### ISSUE THREAD

**Issue by webmeemba** [NathanaelA/nativescript-sqlite#123]
Hi, you could grant me access to a demo to visualize the multithreading performance. Before making your purchase.
Thank you

**Comment by NathanaelA** [comment]
@webmeemba - The normal demo is the same demo in this repo; if you look in the source code you will see where it checks to see if the different components are installed and activates them. 

https://github.com/NathanaelA/nativescript-sqlite/blob/master/demo/app/main-page.js#L48

However, without having the commercial components installed you won't see it, since the demo is smart enough to ignore features you don't have installed.    :grinning:

Now as to speed; the speed is the about the same -- it isn't any faster as the time taken to query sqlite is not really any different.  Either method has to spend time querying the data, so you can't really shrink that speed.

However the primary difference is that the main thread is no longer blocked while things are accessing the sqlite.

So this is running the Sqlite query on the main thread...
![Main Thread](https://nativescript.rocks/img/SQLITE-Freeze.gif)

And this one is running the query in a background thread
![Worker](https://nativescript.rocks/img/SQLite-Worker.gif)

The main difference as you can see is that all activity (i.e. watch the animation) on the main thread (which is where your app runs) freezes while it is retrieving and working with the data when it is on the main thread.   When it is running on the background thread; your main thread is free to do other work and so the animation never freezes...

All data is returned via a callback/promise (just as usual); the only change is you set `multithreaded:true` and then it does everything on a background thread.  Once the data has been updated/inserted/retrieved, the main thread is passed any data you have requested from the table so that your own code has no changes.  :grinning:

**Comment by webmeemba** [comment]
NathanaelA Thanks! ...
If exactly what I'm looking for is to avoid the freezing of the main thread, which is waiting for the answer to continue.
I wanted to generate my own worker defining these tasks within it, but I think that the plugin worked for you, should be better optimized and tested. Is there a difference between defining a worker and buying the commercial plugin? Sorry for the questions, but I want to eliminate all doubts.
Thank you!

**Comment by NathanaelA** [comment]
@webmeemba -

There is nothing stopping you from making your own code that runs your stuff on a background thread; it should be as fast. :grinning:   In fact you can probably create a slightly more optimized worker code yourself on a background thread if you wanted to, as you could tune the data to your specific needs; and parse/modify it all before passing it back to the main thread.   However in general my code is very performant; but it is "general" case rather than tuned to a specific project.   

The main thing I designed in my code base is my worker code makes it totally seemless; you can call any sql call from the main thread and it will automatically put all the calls onto the background thread, totally transparent to your program.     This makes is much simpler to program everything, and makes it drop in compatible if you have been already using my plugin for the last couple years. All sqlite calls are handled off thread and you then get your data back to the main thread to do whatever you need to.    In addition  the commercial version also gives you several additional features, including encryption, prepared queries, (& several new features coming soon) etc....   

Hope that helps....
