### ISSUE TITLE
Fails to validate for ad-hoc/enterprise distribution

### ISSUE THREAD

**Issue by nitrotm** [NathanaelA/nativescript-sqlite#125]
When creating an archive from xcode, and trying to publish for ad-hoc distribution, the archive is rejected by apple with following error:

```
        {
            code = 0;
            description = "Failed to verify bitcode in sqlitewrapper.framework/sqlitewrapper:\nerror: Bundle only contains bitcode-marker /var/folders/6b/htlj4_ks3xsfg5c7_7wbwntc0000gn/T/IDEDistributionOptionThinning.Sft/Payload/wespr.app/Frameworks/sqlitewrapper.framework/sqlitewrapper (armv7)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }
```

Apparently, the xcode project must have `ENABLE_BITCODE = NO;` when building a framework:

https://github.com/EddyVerbruggen/nativescript-plugin-firebase/commit/ceac3076e8466ea2c92ce89455b8c660943d0523

**Comment by NathanaelA** [comment]
Thanks for letting me know.

**Comment by NathanaelA** [comment]
@nitrotm  - Can you tell me if you are a paid client or not -- I need to know if this is a priority or something that can wait for a couple weeks for my next release that is currently being worked on.

**Comment by nitrotm** [comment]
No, it's a bit pricey for my use-case. Seems to be a pretty easy fix to apply though.

**Comment by NathanaelA** [comment]
It is a pretty easy fix; but their is time usage on my part for it still, no matter how simple the fix.      Open source doesn't feed my family, and my wife gets very testy with me when she doesn't have money for food.  So, paid stuff always has to have priority.  :grinning:   

That was the reason I asked -- I never want an actual customer to feel like my support isn't superb.  Since open source is free -- it has to always take a lesser priority, so that my actual customers do feel the support is superb, because I have the time for their issues.  :grinning: 

I'll update this issue when I release a new version in a couple weeks with the fix...   Thank you for letting me know about it!

**Comment by nitrotm** [comment]
Sure, I understand and share your concerns ;) Thank you for looking into it when it makes sense to do so.

**Comment by wendt88** [comment]
This plugin seems to work:
https://market.nativescript.org/plugins/nativescript-disable-bitcode

**Comment by NathanaelA** [comment]
This is no longer an issue in v2.6.0
