### ISSUE TITLE
Why multi-threading not supported in free version? :(

### ISSUE THREAD

**Issue by jannomeister** [NathanaelA/nativescript-sqlite#132]
Does it have any example how to implement queries outside the main thread? I really needed to make my queries outside of the main thread, and I can't afford the nativescript-sqlite enterprise version. :(

**Comment by mandar-bhong** [comment]
+1

**Comment by NathanaelA** [comment]
At this moment that is one of the features to encourage people to actually pay for all the hard work put into this plugin. 

Even if your time is only worth say $20 an hour; do you really think that you can get everything this plugin supports working in less than 20 hours on both iOS and Android and have it fully tested.  :grinning:      

In addition since I make my money purely from selling plugins and contract work; if I don't sell plugins (or do contract work) my family doesn't eat.    So features in some of my plugins beyond the basics are paid features...
