### ISSUE TITLE
Point to custom Sqlite3 for paid extension support

### ISSUE THREAD

**Issue by kaustavlahiri** [NathanaelA/nativescript-sqlite#162]
Is it possible to make nativescript-sqite use a custom bundled Sqlite3 instead of the default system one?
We have a requirement to enable database encryption from the app (by using PRAGMA key = 'pwd'). For this to work we need to use a custom sqlite3.c file that has the SEE plugin.

Initially we thought the paid nativescript-sqlite supports encryption but it turns out it can only decrypt?

**Comment by NathanaelA** [comment]
1. This plugin supports both encryption and decryption.
2. You can already use `PRAGMA key='...'`

**Comment by kaustavlahiri** [comment]
PRAGMA key ='somekey' to set encryption on a non encrypted database does not work. If a database is already encrypted, I could decrypt with options:key and then add a new key with PRAGMA rekey = '';

**Comment by NathanaelA** [comment]
Yes, you have to create a new database with encryption (which you can do with a create database command or ship a encrypted db).  You are correct it won't encrypt a un-encrypted database, however you can work around by just create a new database and copy all data from the old database and then delete the old un-encrypted version.  

 However, for security; if you are wanting to have encrypted db's it is better to start with a encrypted database rather than a unencrypted database.

**Comment by kaustavlahiri** [comment]
Thanks for confirming.
What you are saying, is indeed one of my options: Ship an encrypted database with the app to begin with --> decrypt with your plugin --> rekey as needed.

I would have to explore the other approach you suggested aka create a new encrypted database and then copy over stuff from the old unencrypted one. Although, I don't want to put all this script in the app code. So most likely I won't go with this option. Still its good to know that your plugin can create a new db with encryption turned on.

Finally, just out of continued curiosity, is it possible to make use of a custom sqlite3 library in your plugin? The module.modulemap under platform/ios seems to specify the library. I was wondering if I could do something there to pick up my custom sqlite3.c?

**Comment by NathanaelA** [comment]
Well, we could build you a custom version with your sqlite3.c file; it is basically just building a new aar (on android) and framework on ios to be linked in and using them as the native part.   The rest of the code base (like the JS) would work with no other changes; so it is really just creating new native libraries using he SEE version of sqlite instead of SqlCipher.

**Comment by kaustavlahiri** [comment]
Got it. Thats exactly what I was looking for. Infact, we have got around this use case by using open source SqlCipher to initially encrypt the database during the build phase and then use your paid plugin to decrypt and rekey as needed. So I am good now. Its still good to know that you can package a custom sqlite version, if needed. Thank you!
