### ISSUE TITLE
Execsql failed to prepare:1

### ISSUE THREAD

**Issue by jthompsonmunsterbovine** [NathanaelA/nativescript-sqlite#167]
Hi,

Under what conditions is this error returned? I am using it to execute an insert statement. Will it occur if the sql is not syntactally valid? The error has only occured on 5 devices out of around 100. Is there anything divice specific that could cause the error e.g. free storage space etc.

Thanks

Jason

**Comment by NathanaelA** [comment]
Normally this means your SQL is not correct, if you are dynamically creating sql, it is possible you are messing up the syntax.   

However, there is also the possibility that because all the devices do have older versions of SQLite installed (this driver uses whatever SQLite the manufacturer ships on the device, and it WILL be different per device per manufacturer) is having issues with your sql statement.   If you want to control the SQLite version and ship a modern version of the engine then you need to use the NS-SQlite-Encrypted which then allows you to ship a recent version of the SQLite engine in your app.

**Comment by jthompsonmunsterbovine** [comment]
Thankyou @NathanaelA, bad sql was the problem.
