### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by georgeedwards** [NathanaelA/nativescript-sqlite#23]
Apologies if I have missed it, but it would be really useful if this plugin supported TypeScript, i.e. had a typescript definition file with it. I am happy to help with this if required.

**Comment by NathanaelA** [comment]
The new commercial version does; this feature will make it into the free version when I release the multithreading support in the commercial version.

**Comment by NathanaelA** [comment]
Nope, at this point the typings are still only available in the commercial version.

**Comment by brysem** [comment]
@jacargentina, you can make your own typescript definition file for this package. I have made one with most of the functions based on the free version.

I'll refrain from sharing it here though as I am not sure if @NathanaelA would accept a PR for this since it possibly crashes with his commercial interests. If not an issue I'll gladly submit it as a PR.
