### ISSUE TITLE
NSFileManager.defaultManager is not a function

### ISSUE THREAD

**Issue by NikitaKurdin** [NathanaelA/nativescript-sqlite#57]
Hello.
I have a problem when trying to build an app by Telerik on iOS.
Android is fine.

Here is a screenshot from NativeScript app http://joxi.ru/L21JEjnI8BayYA

package.json:
`"dependencies": {
    "nativescript-sqlite": "^1.1.7",
    "nativescript-telerik-ui": "^1.6.2",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "^3.1.1",
    "tns-core-modules-snapshot": "2.5.0-5.5.372.32"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*"
  }`

At 65 line in calendar.js:
`if (!sqlite.exists(dbname)) { `

**Comment by NathanaelA** [comment]
I would try "tns plugin remove sqlite && tns plugin add sqlite@latest" and see if that helps you.

**Comment by NikitaKurdin** [comment]
Same bug.

**Comment by NathanaelA** [comment]
Which line number is it throwing on now with v1.19?

**Comment by NikitaKurdin** [comment]
Same lines.
iOS 10.3 iPhone 6S

**Comment by NathanaelA** [comment]
Hmm, that doesn't make any sense, the NSFileManger is not on line 681 in v1.1.7 or v1.1.9 and so it should be occurring on a different line; this seems like you are somehow using a very old version.    

According to the git logs and the picture you showed above; the only time that the `exists` function existed with the `NSFileManager` on line 681 was versions:  1.05 - 1.07 --- there have been 9 or 10 updates since that point, including the fix for what you are running into.  

All versions past those have the `exists` function and `NSFileManager` on different lines.

If you can verify /node_modules/nativescript-sqlite is v1.1.9 then you may need to de-install the application from the phone and then try a `tns plaform remove ios` and then `tns platform add ios@2.5.0`  (Assuming you are using the 2.5.0 runtime).   Then try `tns run ios` after that; so you get a full rebuild of the application.

**Comment by NikitaKurdin** [comment]
Hello, sorry for late answer.
I'm build an app in Telerik platform. 
Here is package.json in the project http://joxi.ru/EA4bBp7hwz6MMm
And here is the log
`npm WARN deprecated nativescript-dev-android-snapshot@0.0.11: The nativescript-dev-android-snapshot plugin is now deprecated. Use nativescript-dev-webpack plugin instead.
~\22.09.17 - 1
+-- babel-traverse@6.4.5 
| +-- babel-code-frame@6.26.0 
| | +-- chalk@1.1.3 
| | | +-- ansi-styles@2.2.1 
| | | +-- escape-string-regexp@1.0.5 
| | | +-- has-ansi@2.0.0 
| | | | `-- ansi-regex@2.1.1 
| | | +-- strip-ansi@3.0.1 
| | | `-- supports-color@2.0.0 
| | `-- js-tokens@3.0.2 
| +-- babel-messages@6.23.0 
| | `-- babel-runtime@6.26.0 
| |   +-- core-js@2.5.1 
| |   `-- regenerator-runtime@0.11.0 
| +-- babel-runtime@5.8.38 
| | `-- core-js@1.2.7 
| +-- debug@2.6.8 
| | `-- ms@2.0.0 
| +-- globals@8.18.0 
| +-- invariant@2.2.2 
| | `-- loose-envify@1.3.1 
| +-- lodash@3.10.1 
| `-- repeating@1.1.3 
|   `-- is-finite@1.0.2 
|     `-- number-is-nan@1.0.1 
+-- babel-types@6.4.5 
| +-- esutils@2.0.2 
| `-- to-fast-properties@1.0.3 
+-- babylon@6.4.5 
+-- lazy@1.0.11 
+-- nativescript-dev-android-snapshot@0.0.11 
| +-- adm-zip@0.4.7 
| +-- nativescript-hook@0.2.1 
| | +-- glob@6.0.4 
| | | +-- inflight@1.0.6 
| | | | `-- wrappy@1.0.2 
| | | +-- inherits@2.0.3 
| | | +-- minimatch@3.0.4 
| | | | `-- brace-expansion@1.1.8 
| | | |   +-- balanced-match@1.0.0 
| | | |   `-- concat-map@0.0.1 
| | | +-- once@1.4.0 
| | | `-- path-is-absolute@1.0.1 
| | `-- mkdirp@0.5.1 
| |   `-- minimist@0.0.8 
| +-- semver@5.4.1 
| `-- shelljs@0.6.1 
+-- nativescript-sqlite@1.1.9 
+-- nativescript-telerik-ui@3.1.1 
+-- nativescript-theme-core@1.0.4 
+-- tns-core-modules@3.1.0 
| `-- tns-core-modules-widgets@3.1.0 
`-- tns-core-modules-snapshot@2.5.3-5.5.372.32 
npm WARN 5a6f1dbc-c399-427c-8398-f7e3d406048f No repository field.`

**Comment by NathanaelA** [comment]
There appears to be an issue with the Telerik platform.   
1. Your error message is saying it is a really old version of ns-sqlite; but your package is correct.  So the platform that it created to build it is corrupted somehow with a really old version.
2. You shouldn't have tns-core-modules-snapshot@2.5.3; this is a snapshot of a really old version of the core modules.

**Comment by NikitaKurdin** [comment]
Ok, thanks.
