### ISSUE TITLE
Sqlite.copyDatabase() not working - File not found

### ISSUE THREAD

**Issue by Muhammadinaam** [NathanaelA/nativescript-sqlite#62]
I dropped fit.db file in app folder but I am getting following error:

ERROR Error: java.io.FileNotFoundException: app/fit.db

![ts error](https://user-images.githubusercontent.com/22542738/31771058-109c33c4-b4f4-11e7-8f70-9466f1c7bd2e.png)

**Comment by Muhammadinaam** [comment]
A question on stackoverflow with no answer https://stackoverflow.com/questions/43860519/js-error-uncaught-in-promise-error-java-io-filenotfoundexception

**Comment by Muhammadinaam** [comment]
No solution found for this.
http://disq.us/p/1n4qovb

**Comment by NathanaelA** [comment]
I'm not sure why you are seeing any issues -- Which version of Android is your emulator using?

**Comment by Muhammadinaam** [comment]
Android 8.0
Nexus 5X API 26

![image](https://user-images.githubusercontent.com/22542738/31871505-48c673cc-b7ce-11e7-9e15-8d2bd77b29b0.png)

**Comment by JoelP121** [comment]
I'm having the same issue. Nexus 9_ API 25
![notworking](https://user-images.githubusercontent.com/33731888/32910385-0cbae374-cad7-11e7-8b66-5b2a97fcae8c.PNG)

**Comment by Piovesan121** [comment]
The issue is the db file isn't being moved to /app on the device with the other files. So I probably rebuilt and tried to move/rename/newdb file 20 times as well had maybe 30 debug.logs running attempting to find the problem. And it poof, it started working. I'm not sure what kind of black magic NativeScript is running... beat that dead horse with a stick and I'm sure it will come back to life.

**Comment by NathanaelA** [comment]
NativeScript will frequently try and make the update process quick; however it will miss files.  Your safest bet when adding a new DB is to delete the app off your phone/emulator; then do a `tns build android` (or ios), then a `tns run android`.     This will typically fix it so that the new version of the app has the db in it.

**Comment by NathanaelA** [comment]
I have double checked this functionality with the all new v2.0 release; and it is working as expected on both real phones and emulators.    

Please note: when adding a new database to your app (and you are testing it on your device); you MUST delete the app off your device (i.e. deinstall it); and then you MUST rebuild the app using `tns build android` (or ios) ; then finally using a `tns run android` (or ios).  This way you get a totally fresh copy of the app on your device.

**Comment by rogertthat** [comment]
This is happening for me as well, on actual Android (local build), Android emulator (local build), and BUT NOT on an actual iPhone (cloud build). Just upgraded to 3.4.1, but it may have been broken prior to the upgrade as well on Android. I've tried to remove the app and launching fresh on all 3 devices, but always it's the File Not Found error on Android, but not on iOS. I have confirmed my .db is under app/ and the database is very small (less than 20KB).

Emulator:

> Name: Nexus_5X_API_27_x86
CPU/ABI: Google APIs Intel Atom (x86)
Path: C:\Users\me\.android\avd\Nexus_5X_API_27_x86.avd
Target: google_apis [Google APIs] (API level 27)
Skin: nexus_5x
SD Card: 800M
Snapshot: no
hw.dPad: no
hw.lcd.height: 1920
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: Nexus 5X
vm.heapSize: 256
hw.device.manufacturer: Google
hw.lcd.width: 1080
hw.gps: yes
image.androidVersion.api: 27
hw.audioInput: yes
image.sysdir.1: system-images\android-27\google_apis\x86\
tag.id: google_apis
hw.camera.back: emulated
hw.mainKeys: no
AvdId: Nexus_5X_API_27_x86
hw.camera.front: emulated
hw.lcd.density: 420
avd.ini.displayname: Nexus 5X API 27 x86
hw.gpu.mode: auto
snapshot.present: no
hw.device.hash2: MD5:bc5032b2a871da511332401af3ac6bb0
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
hw.battery: yes
hw.cpu.ncore: 4
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

Actual Android:

> Galaxy S8 (Android 7.0, Kernel 4.4.16-12551610)

Error:

> ActivityManager: Start proc 5225:com.singularsound.mcp1/u0a87 for activity com.singularsound.mcp1/com.tns.NativeScriptActivity
01-25 17:28:16.524  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethodNative(Native Method)
01-25 17:28:16.524  5225  5225 E AndroidRuntime:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
01-25 17:28:16.524  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
01-25 17:28:16.524  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:957)
01-25 17:28:16.524  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:941)
01-25 17:28:16.524  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:933)
01-25 17:28:16.525  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethodNative(Native Method)
01-25 17:28:16.525  5225  5225 E AndroidRuntime:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
01-25 17:28:16.525  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
01-25 17:28:16.525  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:957)
01-25 17:28:16.525  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:941)
01-25 17:28:16.525  5225  5225 E AndroidRuntime:     com.tns.Runtime.callJSMethod(Runtime.java:933)
01-25 17:28:16.527  5225  5225 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)
01-25 17:28:16.527  5225  5225 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
01-25 17:28:16.527  5225  5225 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
01-25 17:28:16.527  5225  5225 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
01-25 17:28:16.527  5225  5225 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
01-25 17:28:16.527  5225  5225 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.singularsound.mcp1/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err:
System.err: Error: java.io.FileNotFoundException: app/mcp_seed_v1.db

**Comment by rogertthat** [comment]
@NathanaelA Would spaces in the path to the app folder be causing an issue on Android (per the bug in my previous post)?

**Comment by NathanaelA** [comment]
Try using the path "~/mcp_seed_v1.db"  the "~" will be converted into the path to your app.  If you try and do relative url's (i.e. `app/mcp_seed_v1.db`) it probably won't be able to find ie...

**Comment by rogertthat** [comment]
@NathanaelA Thanks for the quick response. First, I didn't include the "app/" portion that was reported in the error message (Nativescript automatically put that in when generating the error message). Second, I tried what you suggested and it complains that the name cannot contain a path separator, which further shows that I was only supplying the file name (no path parts) to the copyDatabase call. Below is the code:

`if (!Sqlite.exists("mcp_seed_v1.db"))
        {
            Sqlite.copyDatabase("mcp_seed_v1.db");
        }`

This works just fine on an actual iPhone device. Fails on both Android simulator and actual Android device (Samsung Galaxy S8 in my case), per my previous post. Any further thoughts or work arounds? The App name has a space character, which is why I was asking about that before (reported by someone here: https://github.com/NathanaelA/nativescript-sqlite/issues/21#issuecomment-221567353).

**Comment by NathanaelA** [comment]
Hmm, rats I was hoping it was just a simple relative path issue...

- Have you tried the demo app and seen if it works?
- I haven't tested spaces in the names, it is possible that is messing things up.
- I have a S8 and I can test my test app with it; but it probably won't be for a couple days.

**Comment by rogertthat** [comment]
@NathanaelA I've give the demo a try tomorrow and let you know. Thanks.

**Comment by rogertthat** [comment]
@NathanaelA The demo worked. Then I ported over just the app* and main-page* and database files into my app and the demo also worked there. Then I moved the main-page* files into a sub-folder (thinking maybe that was the issue) and the demo still worked. Then I changed the name of the database file to the same name as mine and the demo still worked. Then removed the demo app* and main-page* files (so that it is now running my app files) and low-and-behold my app now loads fine and the "file not found" error magically went away... Keep in mind, I also uninstalled the app every time I made a change, to make sure the database file was not already copied over from a previous successful run. I have no clue now what could have caused the issue.

**Comment by Alpha1001** [comment]
I am getting the same issue. Even when uninstalling the app on my phone , still the same problem!

**Comment by romangorisek** [comment]
I had the same problem and in the end, I fixed it by renaming my database file from *.db to *.sqlite. I'm not sure why that changes anything, but it started working.

**Comment by chebirthou** [comment]
I had the idea to look into the "nativescript.config.ts", what I've found is that -> appPath: 'src',

So I put my "mydatabase.db" into the root of the "src" directory, then magic! It worked
