### ISSUE TITLE
Wrong insertions or no promise returned with multiple INSERT queries

### ISSUE THREAD

**Issue by Universi** [NathanaelA/nativescript-sqlite#73]
Hi,

I'm facing a wrong result when I insert multiple records with a loop, using `execSql()`
Sometimes (about once in 7), one of my 30 records is inserted with a '1' number in a 'name' column, instead of the expected label.
Sometimes again, the insertions stop for no apparent reason before the last record (29 out of 30). The latest promise doesn't return anything.

Is it because the INSERT queries are not designed to be used in loops?
Is the only possible way then to use prepared statements in a transaction with the commercial version of the plugin?

Thanks in advance,
Regards

**Comment by NathanaelA** [comment]
I've used Loops with it fine, long before I added transactions and prepared statements.     

However, you have to remember JavaScript scopes; and issues that can be caused by them:
If you do:
```js
for (var i=0;i<10;i++) {
  do_blah( () => { do_sql(i); } );
}

```
At the point you call `do_sql`; `i` could be 0 or it could be 10 (or any number between).    

---

For me to fix the issue; I would have to be able to duplicate it.  So if you can create a test case that fails frequently; I'll get it fixed.

**Comment by Universi** [comment]
Thank you for your quick response.
I'm going to check again my loops.

**Comment by NathanaelA** [comment]
Can you tell me if this was occurring on iOS?    I just fixed a random data corruption issue on iOS.

**Comment by Universi** [comment]
Yes, it occurred on iOS. A '1' (or rarely a '0') was sometimes inserted in the same column 'name', on one or two records.

**Comment by NathanaelA** [comment]
Well version 2.20 should hopefully fix it for you.  :grinning:

**Comment by Universi** [comment]
I thank you so much!
