### ISSUE TITLE
nativescript-sqlite-encrypted and nativescript-couchbaselite not working together

### ISSUE THREAD

**Issue by isaacfi** [NathanaelA/nativescript-sqlite#79]
These plugins uses the sqlcipher to encrypt the Database, but they use different versions,

nativescript-sqlite-encrypted uses: 3.5.7
nativescript-coucnhabselite uses: 1.4

This causes this error:

**> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86_64/libsqlcipher.so
        File1: C:\Users\rashe\.android\build-cache\f8469a7464375fbea3247700aa6c6de88b7ca6ae\output\jni
        File2: C:\Users\rashe\.android\build-cache\b6da56e8cf3186a51c37ae6a58d94f25845f842f\output\jni**

The incude.gradle in nativescript-sqlite-encrypted:

```
android {
    productFlavors {
        "encryptedsqlite" {
            dimension "encryptedsqlite"
        }
    }
}


dependencies {
    compile 'net.zetetic:android-database-sqlcipher:3.5.7'    
}
```

And the include,gradle in nativescript-coucnhabselite:

```
repositories {
    maven { url 'http://files.couchbase.com/maven2/' }
    jcenter()
}

dependencies {
    compile 'com.couchbase.lite:couchbase-lite-android:1.4.0'
    compile 'com.couchbase.lite:couchbase-lite-android-sqlcipher:1.4.0'
    compile 'com.google.code.gson:gson:2.8.0'

}

android {
    productFlavors {
        "tns-couchbase" {
            dimension "tns-couchbase"
        }
    }
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
    }
}
```

**Comment by NathanaelA** [comment]
Well, that is a nasty issue.   There are a couple ways you can try to proceed.
1st, you can try and remove the `include.gradle` file that is shipped with NativeScript-Sqlite-Encrypted; this will eliminate the duplicated libsqlcipher.so file.

If the one shipped with couchbase is compatible; the actual JS code that is included in my Encrypted plugin will be able to interface with the couchbase version and you should then have access to encryption as part of the normal sqlite.   

If it is NOT compatible; then that makes the issue a lot more complex and the only two ways to fix it would be:
- Figure out what calls are needed to be Couchbase compatible to the normal.  
- Clone and Rename the libsqlcipher.so, and its methods so that it isn't duplicating it.    
\

**Comment by isaacfi** [comment]
You were right Nathan,

I just remove the inclue gradle from the encrypted plugin and it works fine.

Chears.
