### ISSUE TITLE
Blocking

### ISSUE THREAD

**Issue by x4080** [NathanaelA/nativescript-sqlite#8]
Hi Nathan is sqlite blocking in ios and android? Thanks

**Comment by NathanaelA** [comment]
Yes it is.   However, I have learned of a technique on iOS recently that might allow me to make it non blocking on iOS.  I just haven't had time to try it out...

**Comment by x4080** [comment]
Thanks man

**Comment by jeffswitzer** [comment]
Hi Nathan, did you ever find out more about the possibility of nonblocking queries? Even if you don't have time to implement it  any suggestions on how to implement it would be awesome. Just trying to prevent the ui from freezing during queries so that I could show a spinning ActivityIndicator. 

The only thing I've seen is [webworkers](https://www.nativescript.org/blog/using-workers-in-nativescript-to-execute-javascript-on-background-threads), but I'm not sure it would work for moving a large array of objects from the database into my model.
